name: todo_list
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.1
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  build_runner: ^2.3.3
  json_annotation: ^4.0.1
  json_serializable: ^6.1.3
  get_it: ^7.2.0
  dartz: ^0.10.1
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.6
  sqflite: ^2.2.8+4
  sliding_up_panel: ^2.0.0+1
  flutter_colorpicker: ^1.0.3
  flutter_animate: ^4.1.1+1
  datetime_picker_formfield_new: ^2.1.0
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/add_task_button.svg
    - assets/not_found.svg
    - assets/task_img.svg
    - assets/plus.svg

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Black.ttf
        - asset: fonts/Inter-Bold.ttf
        - asset: fonts/Inter-ExtraBold.ttf
        - asset: fonts/Inter-ExtraLight.ttf
        - asset: fonts/Inter-Light.ttf
        - asset: fonts/Inter-Medium.ttf
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-SemiBold.ttf
        - asset: fonts/Inter-Thin.ttf
  
